services:
  db:
    image: mysql:8.4.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: S3cret
      MYSQL_DATABASE: products
      MYSQL_USER: yuji
      MYSQL_PASSWORD: S3cret
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
